[capital_com]
X_CAP_API_KEY = "MKDM5l391KGb5eo9"
identifier = "arshad.emad@gmail.com"
password = "Quiteneat@3"


[gemini]
api_keys = [
    "AIzaSyAqpeu5F69PkcggYFjRk5saI-NqEu6sK_0",
    "AIzaSyB9c_F5ma0zWzkILWjGKj9EnSFLQpd-zKw",
    "AIzaSyAxg5Keaofj9EGmUB5llDL2aRMEqqAcv5g",
    "AIzaSyCaQdJRth9rS3cxSSpPvyqjO2GodFEDIgw",
    "AIzaSyAh8gFjqR5GRLYtY8OUiCk1E4Wx8vp53JQ",
    "AIzaSyByK1W-BHb9cP93wfxKe1ZOk8ZRCt1Ly38",
    "AIzaSyAtubEXxMoRiYxD7SoqhM8weYuD7wvwQ5o",
    "AIzaSyCfhofgxhdvf-5yb1OzoARN6mR77HKuUyI",
    "AIzaSyBIBhEXKz5kM66z4wZqi6aQsl1JrJerMQc",
    "AIzaSyAnuUX6h-GwTKzT3w461T-FiZVGi1X4TBQ",
    "AIzaSyDxrevk9UOiuFjc-2637s-vXbOkQLHqOmw",
    "AIzaSyDzgnHoJwVVyOar-276d8pILFIG_DWLGfM",
    "AIzaSyBGxmdYoW6ZVhgdG0Tz0jHgcgsLqC2IdUc",
    "AIzaSyDrQYFVXHQ6W1WWBhkbvMit3qkS-Ltg4wc",
    "AIzaSyBwbkmGcpniIvoTFUpo9a5ozyO3wGJskXs",
    "AIzaSyDLrocPTJ4Y2KbFVYOs2TeihJ49FBrsgrU"
]